In [1]:
import numpy as np

In [5]:
a=np.array([[1,2,3],[5,8,7]])
print(a)

[[1 2 3]
 [5 8 7]]


In [6]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [7]:
a=np.array([2,4,1,5])
print(a)

[2 4 1 5]


In [8]:
a*3

array([ 6, 12,  3, 15])

In [9]:
a+1

array([3, 5, 2, 6])

In [10]:
a=np.zeros(5)

In [11]:
print(a)

[0. 0. 0. 0. 0.]


In [12]:
Z = np.zeros((10,10))
print("%d bytes" % (Z.size * Z.itemsize))

800 bytes


In [14]:
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [15]:
Z = np.arange(10,50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [16]:
Z = np.arange(9).reshape(3,3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [17]:
Z = np.random.random((3,3,3))
print(Z)

[[[0.9535711  0.86964454 0.86849042]
  [0.9315924  0.68381074 0.33746667]
  [0.60677637 0.50234842 0.81794368]]

 [[0.43128782 0.78178057 0.46133334]
  [0.80697674 0.41954086 0.36073146]
  [0.08731345 0.58505099 0.34760368]]

 [[0.70801085 0.55742504 0.20972208]
  [0.99488815 0.6132329  0.98136132]
  [0.45965882 0.35165442 0.95150163]]]


In [18]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


C:\Users\joy\AppData\Local\Temp\ipykernel_6568\3912170336.py:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
C:\Users\joy\AppData\Local\Temp\ipykernel_6568\3912170336.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
C:\Users\joy\AppData\Local\Temp\ipykernel_6568\3912170336.py:3: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


In [19]:
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

In [20]:
Z = np.random.uniform(0,10,10)

print (Z - Z%1)
print (np.floor(Z))
print (np.ceil(Z)-1)
print (Z.astype(int))
print (np.trunc(Z))

[9. 9. 2. 4. 7. 9. 8. 1. 9. 1.]
[9. 9. 2. 4. 7. 9. 8. 1. 9. 1.]
[9. 9. 2. 4. 7. 9. 8. 1. 9. 1.]
[9 9 2 4 7 9 8 1 9 1]
[9. 9. 2. 4. 7. 9. 8. 1. 9. 1.]


In [21]:
Z = np.linspace(0,1,11,endpoint=False)[1:]
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [22]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

equal = np.allclose(A,B)
print(equal)

equal = np.array_equal(A,B)
print(equal)

False
False
